platform :ios, '7.1'

target :LayoutDemo do

pod 'BMFloatingHeaderCollectionViewLayout', :path => '../BMFloatingHeaderCollectionViewLayout.podspec'
pod 'SSDataSources'

end

target :LayoutDemoTests do
end
